spring:
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      bootstrap-servers: ${spring.embedded.kafka.brokers}
  test:
    mockmvc:
      print: log_debug

nbp:
  service:
    url: localhost:10101/api
